import type { Service, Doctor, ClinicInfo, FAQ, TimeSlot } from '@/types';

export const CLINIC_INFO: ClinicInfo = {
  name: 'Abdalla Eye Clinic',
  nameAr: 'عيادة عبد الله للعيون',
  legalName: 'Abdalla Eye Clinic',
  legalNameAr: 'عيادة عبد الله للعيون',
  description: 'Leading ophthalmology clinic providing comprehensive eye care services in Alexandria, Egypt',
  descriptionAr: 'عيادة عيون متخصصة في الإسكندرية تقدم رعاية شاملة للعين وخدمات تشخيص وعلاج متقدمة.',
  phone: '+201276637774',
  email: 'm.hossam1712@gmail.com',
  address: 'Smouha & Raml Station',
  addressAr: 'سموحة ومحطة الرمل',
  city: 'Alexandria',
  cityAr: 'الإسكندرية',
  postalCode: '21514',
  country: 'Egypt',
  countryAr: 'مصر',
  workingHours: {
    monday: { open: '12:00', close: '21:00', isClosed: false },
    tuesday: { open: '12:00', close: '21:00', isClosed: false },
    wednesday: { open: '12:00', close: '21:00', isClosed: false },
    thursday: { open: '00:00', close: '00:00', isClosed: true },
    friday: { open: '00:00', close: '00:00', isClosed: true },
    saturday: { open: '12:00', close: '21:00', isClosed: false },
    sunday: { open: '12:00', close: '21:00', isClosed: false },
  },
  socialMedia: {
    facebook: 'https://www.facebook.com/Dr.Mohamed.Hossam.Abdalla',
    instagram: 'https://www.instagram.com/dr_m_hossam_abdalla/',
    whatsapp: '+201276637774',
  },
};

export const DOCTORS: Doctor[] = [
  {
    id: 'dr-1',
    name: 'Prof. Ahmed Hossam Abdalla',
    specialty: 'Professor of Ophthalmology',
    qualification: 'Professor of Ophthalmology',
    experience: 0,
    image: '/assets/images/prof-ahmed-hossam-abdalla-card.webp',
    bio: 'Providing expert ophthalmology care at Abdalla Eye Clinic.',
    languages: ['Arabic', 'English'],
  },
  {
    id: 'dr-2',
    name: 'Dr. Mohamed Hossam Abdalla',
    specialty: 'Ophthalmologist',
    qualification: 'Ophthalmologist',
    experience: 0,
    image: '/assets/images/dr-mohamed-hossam-abdalla-card.webp',
    bio: 'Providing comprehensive eye care at Abdalla Eye Clinic.',
    languages: ['Arabic', 'English'],
  },
];

export const SERVICES: Service[] = [
  {
    id: 'service-1',
    slug: 'comprehensive-eye-exam',
    name: 'Comprehensive Eye Exam',
    nameAr: 'فحص العيون الشامل',
    description: 'Complete eye health assessment and vision testing',
    descriptionAr: 'تقييم كامل لصحة العين وقياس النظر',
    icon: 'eye-exam',
    category: 'diagnostic',
    features: [
      'Visual acuity testing',
      'Intraocular pressure measurement',
      'Retinal examination',
      'Visual field testing',
    ],
    featuresAr: ['قياس حدة الإبصار', 'قياس ضغط العين', 'فحص الشبكية', 'اختبار مجال الإبصار'],
  },
  {
    id: 'service-2',
    slug: 'lasik',
    name: 'LASIK Surgery',
    nameAr: 'جراحة الليزك',
    description: 'Laser-assisted refractive eye surgery',
    descriptionAr: 'تصحيح الإبصار بالليزر بدقة وأمان',
    icon: 'lasik',
    category: 'surgical',
    features: [
      'Blade-free LASIK',
      'Custom wavefront technology',
      'FDA approved procedure',
      'Lifetime follow-up care',
    ],
    featuresAr: ['ليزك بدون شفرة', 'تقنية مخصصة حسب قياسات العين', 'إجراء معتمد وآمن', 'متابعة بعد العملية'],
    seoTitle: 'LASIK Surgery in Alexandria',
    seoTitleAr: 'جراحة الليزك في الإسكندرية',
    seoDescription: 'LASIK consultation and laser vision correction assessment at Abdalla Eye Clinic in Alexandria.',
    seoDescriptionAr: 'استشارة الليزك وتقييم تصحيح الإبصار بالليزر في عيادة عبد الله للعيون في الإسكندرية.',
  },
  {
    id: 'service-3',
    slug: 'cataract-surgery',
    name: 'Cataract Surgery',
    nameAr: 'جراحة المياه البيضاء',
    description: 'Advanced intraocular lens implantation',
    descriptionAr: 'إزالة المياه البيضاء وزراعة عدسات داخل العين',
    icon: 'cataract',
    category: 'surgical',
    features: [
      'Phacoemulsification',
      'Premium IOL options',
      'Same-day surgery',
      'Minimal incision technique',
    ],
    featuresAr: ['تفتيت العدسة بالموجات فوق الصوتية', 'خيارات عدسات متقدمة', 'إجراء في نفس اليوم', 'شق جراحي صغير'],
    seoTitle: 'Cataract Surgery in Alexandria',
    seoTitleAr: 'جراحة المياه البيضاء في الإسكندرية',
    seoDescription: 'Cataract evaluation, phacoemulsification, and IOL lens options at Abdalla Eye Clinic in Alexandria.',
    seoDescriptionAr: 'تقييم المياه البيضاء وتفتيت العدسة وزراعة العدسات داخل العين في عيادة عبد الله للعيون في الإسكندرية.',
  },
  {
    id: 'service-4',
    slug: 'glaucoma',
    name: 'Glaucoma Treatment',
    nameAr: 'علاج الجلوكوما',
    description: 'Medical and surgical glaucoma management',
    descriptionAr: 'متابعة وعلاج ارتفاع ضغط العين طبياً وجراحياً',
    icon: 'glaucoma',
    category: 'treatment',
    features: [
      'Pressure monitoring',
      'Medication management',
      'Laser treatment',
      'Minimally invasive glaucoma surgery',
    ],
    featuresAr: ['متابعة ضغط العين', 'تنظيم العلاج الدوائي', 'العلاج بالليزر', 'جراحات جلوكوما دقيقة ومحدودة التدخل'],
    seoTitle: 'Glaucoma Treatment in Alexandria',
    seoTitleAr: 'علاج الجلوكوما في الإسكندرية',
    seoDescription: 'Glaucoma screening, eye pressure monitoring, optic nerve follow-up, drops, laser, and surgical care.',
    seoDescriptionAr: 'فحص الجلوكوما ومتابعة ضغط العين والعصب البصري والقطرات والليزر والجراحة عند الحاجة.',
  },
  {
    id: 'service-5',
    slug: 'retina',
    name: 'Retinal Treatment',
    nameAr: 'علاج الشبكية',
    description: 'Treatment for retinal diseases and conditions',
    descriptionAr: 'تشخيص وعلاج أمراض الشبكية المختلفة',
    icon: 'retina',
    category: 'treatment',
    features: [
      'Diabetic retinopathy treatment',
      'Macular degeneration therapy',
      'Retinal detachment repair',
      'Anti-VEGF injections',
    ],
    featuresAr: ['علاج اعتلال الشبكية السكري', 'علاج التنكس البقعي', 'إصلاح انفصال الشبكية', 'حقن مضادات عامل النمو'],
    seoTitle: 'Retina Specialist Care in Alexandria',
    seoTitleAr: 'رعاية أمراض الشبكية في الإسكندرية',
    seoDescription: 'Retina evaluation for diabetic retinopathy, flashes, floaters, macular disease, and retinal warning symptoms.',
    seoDescriptionAr: 'تقييم الشبكية لاعتلال الشبكية السكري والومضات والعوائم وأمراض مركز الإبصار وأعراض الشبكية التحذيرية.',
  },
  {
    id: 'service-6',
    slug: 'contact-lens-fitting',
    name: 'Contact Lens Fitting',
    nameAr: 'تركيب العدسات اللاصقة',
    description: 'Professional contact lens prescription and fitting',
    descriptionAr: 'اختيار وقياس العدسات اللاصقة المناسبة للعين',
    icon: 'contact-lens',
    category: 'preventive',
    features: [
      'Multi-brand fitting',
      'Specialty lens options',
      'Extended wear lenses',
      'Orthokeratology',
    ],
    featuresAr: ['تجربة أكثر من نوع عدسات', 'عدسات طبية خاصة', 'عدسات للاستخدام الممتد', 'تقويم القرنية الليلي'],
  },
  {
    id: 'service-7',
    slug: 'dry-eye',
    name: 'Dry Eye Treatment',
    nameAr: 'علاج جفاف العين',
    description: 'Comprehensive dry eye syndrome management',
    descriptionAr: 'خطة شاملة لتشخيص وعلاج جفاف العين',
    icon: 'dry-eye',
    category: 'treatment',
    features: [
      'Meibomian gland analysis',
      'Punctal plugs',
      'Intense pulsed light therapy',
      'Artificial tear consultation',
    ],
    featuresAr: ['تحليل غدد ميبوميان', 'سدادات القنوات الدمعية', 'العلاج بالنبضات الضوئية', 'اختيار القطرات المرطبة المناسبة'],
    seoTitle: 'Dry Eye Treatment in Alexandria',
    seoTitleAr: 'علاج جفاف العين في الإسكندرية',
    seoDescription: 'Dry eye diagnosis and treatment for burning, irritation, screen-related symptoms, and tear film problems.',
    seoDescriptionAr: 'تشخيص وعلاج جفاف العين والحرقان والتهيج وأعراض الشاشات ومشكلات طبقة الدموع.',
  },
  {
    id: 'service-8',
    slug: 'pediatric-eye-care',
    name: 'Pediatric Eye Care',
    nameAr: 'رعاية عيون الأطفال',
    description: 'Eye care services for children',
    descriptionAr: 'خدمات فحص وعلاج عيون الأطفال',
    icon: 'pediatric',
    category: 'preventive',
    features: [
      'Amblyopia (lazy eye) treatment',
      'Vision screening',
      'Glasses prescription',
      'Strabismus evaluation',
    ],
    featuresAr: ['علاج كسل العين', 'فحص النظر للأطفال', 'وصف النظارات', 'تقييم الحول'],
  },
  {
    id: 'service-9',
    slug: 'online-eye-tests',
    name: 'Online Eye Tests',
    nameAr: 'اختبارات النظر على الإنترنت',
    description: 'Interactive online screening tools for color vision, central vision, contrast, near vision, and symptoms',
    descriptionAr: 'فحوصات تفاعلية أولية على الإنترنت للألوان والرؤية المركزية والتباين والرؤية القريبة والأعراض',
    icon: 'eye-exam',
    category: 'diagnostic',
    features: [
      'Ishihara color screening',
      'Amsler grid central vision check',
      'Contrast sensitivity screening',
      'Near-vision screening',
      'Symptom triage report',
    ],
    featuresAr: [
      'فحص أولي لرؤية الألوان بلوحات إيشيهارا',
      'شبكة أمسلر لفحص الرؤية المركزية',
      'فحص أولي لحساسية التباين',
      'فحص الرؤية القريبة',
      'تقرير فرز الأعراض',
    ],
    seoTitle: 'Online Eye Tests',
    seoTitleAr: 'اختبارات النظر على الإنترنت',
    seoDescription: 'Try online eye screening checks, then book a calibrated eye exam in Alexandria when results need follow-up.',
    seoDescriptionAr: 'جرّب فحوصات عيون أولية على الإنترنت ثم احجز فحصاً طبياً معايراً في الإسكندرية عند الحاجة للمتابعة.',
  },
];

export const FAQS: FAQ[] = [
  {
    id: 'faq-1',
    question: 'How often should I have an eye exam?',
    answer: 'Most adults should have a comprehensive eye exam every 1-2 years. If you have diabetes, glaucoma, high eye pressure, or vision problems, more frequent visits may be recommended.',
    questionAr: 'كم مرة يجب أن أجري فحصاً للعين؟',
    answerAr: 'ينصح معظم البالغين بإجراء فحص شامل للعين كل سنة إلى سنتين. إذا كنت مصاباً بالسكري أو الجلوكوما أو ارتفاع ضغط العين أو لديك مشكلات في النظر، فقد تحتاج إلى زيارات أكثر تكراراً.',
    category: 'general',
  },
  {
    id: 'faq-2',
    question: 'What should I bring to my first appointment?',
    answer: 'Please bring your ID, previous prescriptions, current medications, medical reports, and any glasses or contact lenses you currently use.',
    questionAr: 'ما الذي يجب أن أحضره في أول زيارة؟',
    answerAr: 'يرجى إحضار بطاقة الهوية، والوصفات السابقة، والأدوية الحالية، والتقارير الطبية، وأي نظارات أو عدسات لاصقة تستخدمها حالياً.',
    category: 'general',
  },
  {
    id: 'faq-3',
    question: 'Do you treat children?',
    answer: 'Yes, we provide eye exams for children and evaluate squint, lazy eye, refractive errors, allergies, and other pediatric eye conditions.',
    questionAr: 'هل تعالجون الأطفال؟',
    answerAr: 'نعم، نقدم فحوصات عيون للأطفال ونقيّم الحول وكسل العين وعيوب الإبصار والحساسية وغيرها من مشكلات عيون الأطفال.',
    category: 'general',
  },
  {
    id: 'faq-4',
    question: 'Can diabetes affect my eyes?',
    answer: 'Yes. Diabetes can lead to diabetic retinopathy, cataracts, and glaucoma. Regular eye exams are important for early detection.',
    questionAr: 'هل يمكن أن يؤثر السكري على العين؟',
    answerAr: 'نعم. قد يؤدي السكري إلى اعتلال الشبكية السكري والمياه البيضاء والجلوكوما. فحوصات العين المنتظمة مهمة للاكتشاف المبكر.',
    category: 'general',
  },
  {
    id: 'faq-5',
    question: 'What are the signs I need an eye doctor?',
    answer: 'Blurred vision, headaches, eye pain, redness, floaters, flashes, dryness, or difficulty seeing at night are common reasons to book an exam.',
    questionAr: 'ما العلامات التي تستدعي زيارة طبيب عيون؟',
    answerAr: 'زغللة الرؤية، والصداع، وألم العين، والاحمرار، والعوائم، والومضات، والجفاف، أو صعوبة الرؤية ليلاً من الأسباب الشائعة لحجز فحص.',
    category: 'general',
  },
  {
    id: 'faq-6',
    question: 'What causes blurry vision?',
    answer: 'Blurry vision may be caused by refractive errors, cataracts, dry eye, retinal problems, glaucoma, or diabetes-related eye disease.',
    questionAr: 'ما أسباب زغللة الرؤية؟',
    answerAr: 'قد تحدث زغللة الرؤية بسبب عيوب الإبصار أو المياه البيضاء أو جفاف العين أو مشكلات الشبكية أو الجلوكوما أو أمراض العين المرتبطة بالسكري.',
    category: 'general',
  },
  {
    id: 'faq-7',
    question: 'Do you accept walk-in patients?',
    answer: 'Appointments are recommended, but we try to accommodate urgent cases and walk-in visits whenever possible.',
    questionAr: 'هل تقبلون المرضى بدون موعد؟',
    answerAr: 'يفضل الحجز المسبق، لكننا نحاول استقبال الحالات العاجلة والزيارات بدون موعد متى أمكن.',
    category: 'general',
  },
  {
    id: 'faq-8',
    question: 'How long does an eye exam take?',
    answer: 'A routine eye exam usually takes 20-45 minutes depending on the tests required.',
    questionAr: 'كم يستغرق فحص العين؟',
    answerAr: 'يستغرق فحص العين الروتيني عادة من 20 إلى 45 دقيقة حسب الفحوصات المطلوبة.',
    category: 'general',
  },
  {
    id: 'faq-9',
    question: 'Can eye problems cause headaches?',
    answer: 'Yes. Eye strain, uncorrected glasses prescription, dry eye, and some eye diseases can contribute to headaches.',
    questionAr: 'هل يمكن أن تسبب مشكلات العين صداعاً؟',
    answerAr: 'نعم. إجهاد العين، أو مقاس النظارة غير المناسب، أو جفاف العين، أو بعض أمراض العين قد تساهم في حدوث الصداع.',
    category: 'general',
  },
  {
    id: 'faq-10',
    question: 'What is dry eye syndrome?',
    answer: 'Dry eye occurs when your eyes do not produce enough tears or the tears evaporate too quickly, causing irritation and burning.',
    questionAr: 'ما هو جفاف العين؟',
    answerAr: 'يحدث جفاف العين عندما لا تنتج العين كمية كافية من الدموع أو عندما تتبخر الدموع بسرعة، مما يسبب تهيجاً وحرقاناً.',
    category: 'general',
  },
  {
    id: 'faq-11',
    question: 'What is LASIK surgery?',
    answer: 'LASIK is a laser procedure that reshapes the cornea to reduce dependence on glasses or contact lenses.',
    questionAr: 'ما هي جراحة الليزك؟',
    answerAr: 'الليزك إجراء بالليزر يعيد تشكيل القرنية لتقليل الاعتماد على النظارات أو العدسات اللاصقة.',
    category: 'lasik',
  },
  {
    id: 'faq-12',
    question: 'Am I a good candidate for LASIK?',
    answer: 'Candidates should have stable vision, healthy corneas, and no major eye disease. A full assessment is required.',
    questionAr: 'هل أنا مرشح مناسب لليزك؟',
    answerAr: 'ينبغي أن يكون النظر مستقراً، والقرنية سليمة، ولا توجد أمراض عيون مهمة. يلزم إجراء تقييم كامل قبل القرار.',
    category: 'lasik',
  },
  {
    id: 'faq-13',
    question: 'Is LASIK surgery safe?',
    answer: 'LASIK is considered safe and effective when performed on suitable candidates by an experienced surgeon.',
    questionAr: 'هل جراحة الليزك آمنة؟',
    answerAr: 'يعتبر الليزك آمناً وفعالاً عند إجرائه للمرضى المناسبين بواسطة جراح خبير.',
    category: 'lasik',
  },
  {
    id: 'faq-14',
    question: 'Does LASIK hurt?',
    answer: 'Most patients feel little to no pain during LASIK. Mild discomfort or dryness afterward is common.',
    questionAr: 'هل الليزك مؤلم؟',
    answerAr: 'يشعر معظم المرضى بألم بسيط جداً أو لا يشعرون بألم أثناء الليزك. قد يحدث انزعاج بسيط أو جفاف بعده.',
    category: 'lasik',
  },
  {
    id: 'faq-15',
    question: 'How long does LASIK take?',
    answer: 'The laser treatment itself takes only a few minutes per eye, while the full visit may take about 1 hour.',
    questionAr: 'كم تستغرق عملية الليزك؟',
    answerAr: 'تستغرق خطوة الليزر نفسها دقائق قليلة لكل عين، بينما قد تستغرق الزيارة كاملة حوالي ساعة.',
    category: 'lasik',
  },
  {
    id: 'faq-16',
    question: 'How soon can I see after LASIK?',
    answer: 'Many patients notice improved vision within 24 hours, with continued improvement over several days.',
    questionAr: 'متى يتحسن النظر بعد الليزك؟',
    answerAr: 'يلاحظ كثير من المرضى تحسناً في النظر خلال 24 ساعة، مع استمرار التحسن خلال عدة أيام.',
    category: 'lasik',
  },
  {
    id: 'faq-17',
    question: 'Is LASIK permanent?',
    answer: 'LASIK permanently reshapes the cornea, but natural aging changes such as reading vision may still occur later.',
    questionAr: 'هل نتيجة الليزك دائمة؟',
    answerAr: 'يعيد الليزك تشكيل القرنية بشكل دائم، لكن تغيرات العمر الطبيعية مثل ضعف رؤية القراءة قد تظهر لاحقاً.',
    category: 'lasik',
  },
  {
    id: 'faq-18',
    question: 'Can I wear contact lenses before LASIK consultation?',
    answer: 'Soft lenses should usually be stopped for several days before evaluation. Rigid lenses may require longer.',
    questionAr: 'هل يمكن ارتداء العدسات قبل استشارة الليزك؟',
    answerAr: 'ينبغي عادة إيقاف العدسات اللينة لعدة أيام قبل التقييم، وقد تحتاج العدسات الصلبة إلى فترة أطول.',
    category: 'lasik',
  },
  {
    id: 'faq-19',
    question: 'What should I avoid after LASIK?',
    answer: 'Avoid rubbing your eyes, swimming, dusty environments, and eye makeup for the period advised by your doctor.',
    questionAr: 'ما الذي يجب تجنبه بعد الليزك؟',
    answerAr: 'تجنب فرك العين، والسباحة، والأماكن المتربة، ومكياج العين خلال الفترة التي يحددها الطبيب.',
    category: 'lasik',
  },
  {
    id: 'faq-20',
    question: 'How long do I need eye drops after LASIK?',
    answer: 'Most patients use prescribed drops for several days to a few weeks depending on healing.',
    questionAr: 'كم مدة استخدام القطرات بعد الليزك؟',
    answerAr: 'يستخدم معظم المرضى القطرات الموصوفة من عدة أيام إلى بضعة أسابيع حسب الالتئام.',
    category: 'lasik',
  },
  {
    id: 'faq-21',
    question: 'What is a cataract?',
    answer: 'A cataract is clouding of the natural lens inside the eye that causes blurry or dim vision.',
    questionAr: 'ما هي المياه البيضاء؟',
    answerAr: 'المياه البيضاء هي عتامة في العدسة الطبيعية داخل العين تسبب زغللة أو ضعفاً في الرؤية.',
    category: 'cataract',
  },
  {
    id: 'faq-22',
    question: 'What are cataract symptoms?',
    answer: 'Blurred vision, glare from lights, faded colors, double vision, and difficulty driving at night are common symptoms.',
    questionAr: 'ما أعراض المياه البيضاء؟',
    answerAr: 'زغللة الرؤية، والوهج من الأضواء، وبهتان الألوان، والرؤية المزدوجة، وصعوبة القيادة ليلاً من الأعراض الشائعة.',
    category: 'cataract',
  },
  {
    id: 'faq-23',
    question: 'When do I need cataract surgery?',
    answer: 'Surgery is recommended when cataracts begin affecting daily activities such as reading, driving, or work.',
    questionAr: 'متى أحتاج إلى جراحة المياه البيضاء؟',
    answerAr: 'ينصح بالجراحة عندما تبدأ المياه البيضاء في التأثير على الأنشطة اليومية مثل القراءة أو القيادة أو العمل.',
    category: 'cataract',
  },
  {
    id: 'faq-24',
    question: 'Is cataract surgery safe?',
    answer: 'Cataract surgery is one of the most common and successful procedures worldwide.',
    questionAr: 'هل جراحة المياه البيضاء آمنة؟',
    answerAr: 'تعد جراحة المياه البيضاء من أكثر العمليات شيوعاً ونجاحاً على مستوى العالم.',
    category: 'cataract',
  },
  {
    id: 'faq-25',
    question: 'How long does cataract surgery take?',
    answer: 'Most cataract procedures take around 15-30 minutes.',
    questionAr: 'كم تستغرق جراحة المياه البيضاء؟',
    answerAr: 'تستغرق معظم عمليات المياه البيضاء حوالي 15 إلى 30 دقيقة.',
    category: 'cataract',
  },
  {
    id: 'faq-26',
    question: 'Is cataract surgery painful?',
    answer: 'The procedure is usually painless with local anesthesia or numbing drops.',
    questionAr: 'هل جراحة المياه البيضاء مؤلمة؟',
    answerAr: 'تكون العملية عادة غير مؤلمة مع التخدير الموضعي أو قطرات التخدير.',
    category: 'cataract',
  },
  {
    id: 'faq-27',
    question: 'How soon can I see after cataract surgery?',
    answer: 'Many patients notice clearer vision within a few days, with full healing over several weeks.',
    questionAr: 'متى يتحسن النظر بعد جراحة المياه البيضاء؟',
    answerAr: 'يلاحظ كثير من المرضى وضوحاً أفضل خلال أيام قليلة، ويكتمل الالتئام خلال عدة أسابيع.',
    category: 'cataract',
  },
  {
    id: 'faq-28',
    question: 'Can cataracts come back after surgery?',
    answer: 'The cataract does not return, but the capsule behind the lens may become cloudy later and can be treated with laser.',
    questionAr: 'هل تعود المياه البيضاء بعد الجراحة؟',
    answerAr: 'لا تعود المياه البيضاء نفسها، لكن قد تصبح الكبسولة خلف العدسة معتمة لاحقاً ويمكن علاجها بالليزر.',
    category: 'cataract',
  },
  {
    id: 'faq-29',
    question: 'When can I drive after cataract surgery?',
    answer: 'This depends on your healing and vision quality. Your doctor will advise when it is safe.',
    questionAr: 'متى يمكنني القيادة بعد جراحة المياه البيضاء؟',
    answerAr: 'يعتمد ذلك على الالتئام وجودة الرؤية. سيخبرك الطبيب بالوقت الآمن للقيادة.',
    category: 'cataract',
  },
  {
    id: 'faq-30',
    question: 'What should I avoid after cataract surgery?',
    answer: 'Avoid rubbing the eye, heavy lifting, dirty water exposure, and activities restricted by your surgeon.',
    questionAr: 'ما الذي يجب تجنبه بعد جراحة المياه البيضاء؟',
    answerAr: 'تجنب فرك العين، وحمل الأشياء الثقيلة، والتعرض للمياه غير النظيفة، وأي أنشطة يمنعها الجراح.',
    category: 'cataract',
  },
  {
    id: 'faq-31',
    question: 'What is an IOL?',
    answer: 'An intraocular lens (IOL) is the artificial lens placed inside the eye during cataract surgery.',
    questionAr: 'ما هي العدسة داخل العين؟',
    answerAr: 'العدسة داخل العين هي عدسة صناعية توضع داخل العين أثناء جراحة المياه البيضاء.',
    category: 'iol',
  },
  {
    id: 'faq-32',
    question: 'What are the different types of IOLs?',
    answer: 'Common options include monofocal, multifocal, extended depth of focus, and toric lenses.',
    questionAr: 'ما أنواع العدسات المزروعة؟',
    answerAr: 'تشمل الخيارات الشائعة العدسات أحادية البؤرة، ومتعددة البؤر، وذات عمق التركيز الممتد، والعدسات التوريك.',
    category: 'iol',
  },
  {
    id: 'faq-33',
    question: 'What is a monofocal lens?',
    answer: 'A monofocal lens provides clear vision at one main distance, usually far vision.',
    questionAr: 'ما هي العدسة أحادية البؤرة؟',
    answerAr: 'توفر العدسة أحادية البؤرة رؤية واضحة على مسافة رئيسية واحدة، غالباً الرؤية البعيدة.',
    category: 'iol',
  },
  {
    id: 'faq-34',
    question: 'What is a multifocal lens?',
    answer: 'A multifocal lens is designed to improve vision at multiple distances and reduce dependence on glasses.',
    questionAr: 'ما هي العدسة متعددة البؤر؟',
    answerAr: 'تصمم العدسة متعددة البؤر لتحسين الرؤية على عدة مسافات وتقليل الاعتماد على النظارات.',
    category: 'iol',
  },
  {
    id: 'faq-35',
    question: 'What is a toric lens?',
    answer: 'A toric lens corrects astigmatism during cataract surgery.',
    questionAr: 'ما هي عدسة التوريك؟',
    answerAr: 'عدسة التوريك تصحح الاستجماتيزم أثناء جراحة المياه البيضاء.',
    category: 'iol',
  },
  {
    id: 'faq-36',
    question: 'Which lens is best for cataract surgery?',
    answer: 'The best lens depends on your eye health, lifestyle, and visual needs.',
    questionAr: 'ما أفضل عدسة لجراحة المياه البيضاء؟',
    answerAr: 'تعتمد أفضل عدسة على صحة العين ونمط الحياة والاحتياجات البصرية.',
    category: 'iol',
  },
  {
    id: 'faq-37',
    question: 'Can I stop wearing glasses after cataract surgery?',
    answer: 'Many patients reduce their need for glasses depending on the chosen lens type.',
    questionAr: 'هل يمكنني الاستغناء عن النظارة بعد جراحة المياه البيضاء؟',
    answerAr: 'يقل احتياج كثير من المرضى للنظارات حسب نوع العدسة المختارة.',
    category: 'iol',
  },
  {
    id: 'faq-38',
    question: 'How long do lens implants last?',
    answer: 'IOLs are designed to be permanent and usually last for life.',
    questionAr: 'كم تدوم العدسات المزروعة؟',
    answerAr: 'تصمم العدسات المزروعة لتكون دائمة وغالباً تستمر مدى الحياة.',
    category: 'iol',
  },
  {
    id: 'faq-39',
    question: 'Are premium lenses worth it?',
    answer: 'Premium lenses may benefit patients who want more freedom from glasses, depending on eligibility.',
    questionAr: 'هل العدسات المتقدمة تستحق الاختيار؟',
    answerAr: 'قد تفيد العدسات المتقدمة المرضى الذين يرغبون في حرية أكبر من النظارات، حسب ملاءمة الحالة.',
    category: 'iol',
  },
  {
    id: 'faq-40',
    question: 'Can I choose my lens implant?',
    answer: 'Yes, after examination and discussion with your surgeon.',
    questionAr: 'هل يمكنني اختيار العدسة المزروعة؟',
    answerAr: 'نعم، بعد الفحص ومناقشة الخيارات مع الجراح.',
    category: 'iol',
  },
  {
    id: 'faq-41',
    question: 'What is glaucoma?',
    answer: 'Glaucoma is a disease that damages the optic nerve, often related to high eye pressure.',
    questionAr: 'ما هي الجلوكوما؟',
    answerAr: 'الجلوكوما مرض يسبب تلفاً في العصب البصري، وغالباً يرتبط بارتفاع ضغط العين.',
    category: 'glaucoma',
  },
  {
    id: 'faq-42',
    question: 'Does glaucoma have symptoms?',
    answer: 'Early glaucoma often has no symptoms, which is why regular screening is important.',
    questionAr: 'هل للجلوكوما أعراض؟',
    answerAr: 'غالباً لا تسبب الجلوكوما المبكرة أعراضاً، لذلك فإن الفحص المنتظم مهم.',
    category: 'glaucoma',
  },
  {
    id: 'faq-43',
    question: 'Can glaucoma cause blindness?',
    answer: 'Untreated glaucoma can lead to permanent vision loss.',
    questionAr: 'هل يمكن أن تسبب الجلوكوما العمى؟',
    answerAr: 'قد تؤدي الجلوكوما غير المعالجة إلى فقدان دائم في النظر.',
    category: 'glaucoma',
  },
  {
    id: 'faq-44',
    question: 'Is glaucoma hereditary?',
    answer: 'Yes, family history increases the risk of glaucoma.',
    questionAr: 'هل الجلوكوما وراثية؟',
    answerAr: 'نعم، وجود تاريخ عائلي يزيد خطر الإصابة بالجلوكوما.',
    category: 'glaucoma',
  },
  {
    id: 'faq-45',
    question: 'How is glaucoma treated?',
    answer: 'Treatment may include eye drops, laser treatment, or surgery.',
    questionAr: 'كيف يتم علاج الجلوكوما؟',
    answerAr: 'قد يشمل العلاج قطرات العين أو الليزر أو الجراحة.',
    category: 'glaucoma',
  },
  {
    id: 'faq-46',
    question: 'Do glaucoma eye drops need lifelong use?',
    answer: 'Many patients need long-term treatment, but management depends on each case.',
    questionAr: 'هل تحتاج قطرات الجلوكوما إلى استخدام مدى الحياة؟',
    answerAr: 'يحتاج كثير من المرضى إلى علاج طويل المدى، لكن الخطة تعتمد على كل حالة.',
    category: 'glaucoma',
  },
  {
    id: 'faq-47',
    question: 'How often should glaucoma patients be checked?',
    answer: 'Follow-up visits vary, but regular monitoring is essential.',
    questionAr: 'كم مرة يجب متابعة مريض الجلوكوما؟',
    answerAr: 'تختلف مواعيد المتابعة، لكن المراقبة المنتظمة ضرورية.',
    category: 'glaucoma',
  },
  {
    id: 'faq-48',
    question: 'What is glaucoma surgery?',
    answer: 'Glaucoma surgery helps lower eye pressure when drops or laser are not enough.',
    questionAr: 'ما هي جراحة الجلوكوما؟',
    answerAr: 'تساعد جراحة الجلوكوما على خفض ضغط العين عندما لا تكون القطرات أو الليزر كافية.',
    category: 'glaucoma',
  },
  {
    id: 'faq-49',
    question: 'Can glaucoma be cured?',
    answer: 'Damage from glaucoma cannot be reversed, but treatment helps control progression.',
    questionAr: 'هل يمكن شفاء الجلوكوما؟',
    answerAr: 'لا يمكن عادة عكس التلف الناتج عن الجلوكوما، لكن العلاج يساعد على التحكم في تقدم المرض.',
    category: 'glaucoma',
  },
  {
    id: 'faq-50',
    question: 'Why choose our eye clinic in Alexandria, Egypt?',
    answer: 'We provide modern diagnostics, personalized treatment plans, surgical expertise, and compassionate care for patients in Alexandria and surrounding areas.',
    questionAr: 'لماذا تختار عيادتنا للعيون في الإسكندرية، مصر؟',
    answerAr: 'نقدم تشخيصاً حديثاً، وخطط علاج شخصية، وخبرة جراحية، ورعاية إنسانية للمرضى في الإسكندرية والمناطق المحيطة.',
    category: 'glaucoma',
  },
];

export const CLINIC_BRANCHES = [
  {
    slug: 'smouha',
    name: 'Smouha Branch',
    address: 'Wataneya Medical Center, 14th May Street, above Alexandria Pediatric Center, 4th floor',
    addressAr: 'المركز الطبي الوطنية، شارع 14 مايو، أعلى مركز الإسكندرية للأطفال، الدور الرابع',
    phone: '+2033856404',
    hours: '12:00 PM - 9:00 PM',
    landmarks: ['14th May Street', 'Alexandria Pediatric Center', 'Smouha medical district'],
    landmarksAr: ['شارع 14 مايو', 'مركز الإسكندرية للأطفال', 'منطقة سموحة الطبية'],
    mapUrl:
      'https://www.google.com/maps/search/?api=1&query=Abdalla%20Eye%20Clinic%20Wataneya%20Medical%20Center%2014th%20May%20Street%20Smouha%20Alexandria%20Egypt',
    googleMapsPlaceUrl:
      'https://www.google.com/maps/search/?api=1&query=Abdalla%20Eye%20Clinic%20Wataneya%20Medical%20Center%2014th%20May%20Street%20Smouha%20Alexandria%20Egypt',
    googleMapsDirectionsUrl:
      'https://www.google.com/maps/dir/?api=1&destination=Abdalla%20Eye%20Clinic%20Wataneya%20Medical%20Center%2014th%20May%20Street%20Smouha%20Alexandria%20Egypt',
    // TODO: Replace with the verified Google Maps Place ID when the branch profile is available.
    googleMapsPlaceId: null,
    // TODO: Replace null values with verified branch-level coordinates from Google Business Profile or Google Maps.
    geo: {
      latitude: null,
      longitude: null,
    },
  },
  {
    slug: 'raml-station',
    name: 'Raml Station Branch',
    address: '22 Al-Ghorfa Al-Togareya Street, 3rd floor',
    addressAr: '22 شارع الغرفة التجارية، محطة الرمل، الدور الثالث',
    phone: '+2034805023',
    hours: '12:00 PM - 9:00 PM',
    landmarks: ['Raml Station', 'Al-Ghorfa Al-Togareya Street', 'Downtown Alexandria'],
    landmarksAr: ['محطة الرمل', 'شارع الغرفة التجارية', 'وسط الإسكندرية'],
    mapUrl:
      'https://www.google.com/maps/search/?api=1&query=Abdalla%20Eye%20Clinic%2022%20Al-Ghorfa%20Al-Togareya%20Street%20Raml%20Station%20Alexandria%20Egypt',
    googleMapsPlaceUrl:
      'https://www.google.com/maps/search/?api=1&query=Abdalla%20Eye%20Clinic%2022%20Al-Ghorfa%20Al-Togareya%20Street%20Raml%20Station%20Alexandria%20Egypt',
    googleMapsDirectionsUrl:
      'https://www.google.com/maps/dir/?api=1&destination=Abdalla%20Eye%20Clinic%2022%20Al-Ghorfa%20Al-Togareya%20Street%20Raml%20Station%20Alexandria%20Egypt',
    // TODO: Replace with the verified Google Maps Place ID when the branch profile is available.
    googleMapsPlaceId: null,
    // TODO: Replace null values with verified branch-level coordinates from Google Business Profile or Google Maps.
    geo: {
      latitude: null,
      longitude: null,
    },
  },
];

export const BRANCH_FAQS: Record<string, FAQ[]> = {
  smouha: [
    {
      id: 'branch-smouha-parking',
      question: 'Where is the Smouha branch located?',
      answer:
        'The Smouha branch is at Wataneya Medical Center on 14th May Street, above Alexandria Pediatric Center, 4th floor.',
      questionAr: 'أين يقع فرع سموحة؟',
      answerAr:
        'يقع فرع سموحة في المركز الطبي الوطنية بشارع 14 مايو، أعلى مركز الإسكندرية للأطفال، الدور الرابع.',
      category: 'branch-smouha',
    },
    {
      id: 'branch-smouha-services',
      question: 'Which services are available at the Smouha branch?',
      answer:
        'The Smouha branch supports eye exams, LASIK consultation, cataract assessment, glaucoma follow-up, retina checks, dry eye care, and pediatric eye care.',
      questionAr: 'ما الخدمات المتاحة في فرع سموحة؟',
      answerAr:
        'يوفر فرع سموحة فحوصات العين واستشارات الليزك وتقييم المياه البيضاء ومتابعة الجلوكوما وفحوصات الشبكية وعلاج جفاف العين ورعاية عيون الأطفال.',
      category: 'branch-smouha',
    },
    {
      id: 'branch-smouha-booking',
      question: 'How can I book the Smouha branch?',
      answer:
        'You can call the branch phone number, contact the clinic on WhatsApp, or book through the online appointment form.',
      questionAr: 'كيف أحجز في فرع سموحة؟',
      answerAr:
        'يمكنك الاتصال برقم الفرع أو التواصل مع العيادة عبر واتساب أو الحجز من خلال نموذج المواعيد على الموقع.',
      category: 'branch-smouha',
    },
  ],
  'raml-station': [
    {
      id: 'branch-raml-location',
      question: 'Where is the Raml Station branch located?',
      answer: 'The Raml Station branch is at 22 Al-Ghorfa Al-Togareya Street, 3rd floor, Downtown Alexandria.',
      questionAr: 'أين يقع فرع محطة الرمل؟',
      answerAr: 'يقع فرع محطة الرمل في 22 شارع الغرفة التجارية، الدور الثالث، وسط الإسكندرية.',
      category: 'branch-raml-station',
    },
    {
      id: 'branch-raml-services',
      question: 'Which services are available at the Raml Station branch?',
      answer:
        'The Raml Station branch supports comprehensive eye exams, cataract and glaucoma follow-up, retina assessment, dry eye treatment, and LASIK consultation.',
      questionAr: 'ما الخدمات المتاحة في فرع محطة الرمل؟',
      answerAr:
        'يوفر فرع محطة الرمل فحص العين الشامل ومتابعة المياه البيضاء والجلوكوما وتقييم الشبكية وعلاج جفاف العين واستشارات الليزك.',
      category: 'branch-raml-station',
    },
    {
      id: 'branch-raml-booking',
      question: 'How can I book the Raml Station branch?',
      answer:
        'You can call the branch phone number, contact the clinic on WhatsApp, or book through the online appointment form.',
      questionAr: 'كيف أحجز في فرع محطة الرمل؟',
      answerAr:
        'يمكنك الاتصال برقم الفرع أو التواصل مع العيادة عبر واتساب أو الحجز من خلال نموذج المواعيد على الموقع.',
      category: 'branch-raml-station',
    },
  ],
};

export const NAVIGATION_ITEMS = [
  { href: '/', label: 'home' },
  { href: '/services', label: 'services' },
  { href: '/doctors', label: 'doctors' },
  { href: '/eye-tests', label: 'eye_tests' },
  { href: '/about', label: 'about' },
  { href: '/blog', label: 'blog' },
  { href: '/contact', label: 'contact' },
  { href: '/faqs', label: 'faqs' },
];

export const APPOINTMENT_TIME_SLOTS = [
  '12:00',
  '12:30',
  '13:00',
  '13:30',
  '14:00',
  '14:30',
  '15:00',
  '15:30',
  '16:00',
  '16:30',
  '17:00',
  '17:30',
  '18:00',
  '18:30',
  '19:00',
  '19:30',
  '20:00',
  '20:30',
];
