/**
 * Reads all URLs from the sitemap generated by `next build` and submits them to
 * Bing's IndexNow endpoint.
 *
 * Prerequisites:
 *   1. Set INDEXNOW_KEY in your Vercel environment variables (Settings → Environment Variables).
 *   2. Add a file at public/<key>.txt whose sole content is that same key string.
 *      IndexNow uses this file to verify you own the domain.
 *
 * The script is a no-op when:
 *   - INDEXNOW_KEY is not set (local builds without the env var).
 *   - VERCEL_ENV is set to something other than "production" (preview deployments).
 *
 * Errors are logged but do NOT fail the build (non-zero exit), so a transient
 * network blip never blocks a deployment.
 */

import { readFileSync } from 'fs';
import { join } from 'path';

const SITE_URL = 'https://www.abdallaeyeclinic.com';
const SITEMAP_URL = `${SITE_URL}/sitemap.xml`;
const INDEXNOW_ENDPOINT = 'https://api.indexnow.org/IndexNow';
const BATCH_SIZE = 10_000; // IndexNow maximum URLs per request

// ─── Helpers ─────────────────────────────────────────────────────────────────

function extractUrls(xml: string): string[] {
  return Array.from(
    xml.matchAll(/<loc>(https?:\/\/[^<]+)<\/loc>/g),
    (m) => m[1],
  );
}

/** Reads the sitemap Next.js writes to disk during `next build`. */
function readBuiltSitemap(): string[] {
  const artifactPath = join(
    process.cwd(),
    '.next/server/app/sitemap.xml.body',
  );
  return extractUrls(readFileSync(artifactPath, 'utf-8'));
}

/** Falls back to fetching the live sitemap when the build artifact is absent. */
async function fetchLiveSitemap(): Promise<string[]> {
  const res = await fetch(SITEMAP_URL);
  if (!res.ok) {
    throw new Error(`Sitemap fetch failed: HTTP ${res.status}`);
  }
  return extractUrls(await res.text());
}

async function resolveUrls(): Promise<string[]> {
  try {
    const urls = readBuiltSitemap();
    console.log(`IndexNow: read ${urls.length} URLs from build artifact.`);
    return urls;
  } catch {
    console.log('IndexNow: build artifact not found — fetching live sitemap…');
    const urls = await fetchLiveSitemap();
    console.log(`IndexNow: fetched ${urls.length} URLs from ${SITEMAP_URL}.`);
    return urls;
  }
}

async function submitUrls(urls: string[], key: string): Promise<void> {
  const host = new URL(SITE_URL).hostname;
  const keyLocation = `${SITE_URL}/${key}.txt`;

  for (let i = 0; i < urls.length; i += BATCH_SIZE) {
    const batch = urls.slice(i, i + BATCH_SIZE);
    const batchNum = Math.floor(i / BATCH_SIZE) + 1;

    const res = await fetch(INDEXNOW_ENDPOINT, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json; charset=utf-8' },
      body: JSON.stringify({ host, key, keyLocation, urlList: batch }),
    });

    // 200 = key verified + URLs accepted; 202 = accepted, key verification pending.
    // Both are success. Any other status is an error.
    if (!res.ok && res.status !== 202) {
      const body = await res.text().catch(() => '');
      throw new Error(`IndexNow responded ${res.status}: ${body}`);
    }

    console.log(
      `IndexNow: batch ${batchNum} — submitted ${batch.length} URLs → HTTP ${res.status}`,
    );
  }
}

// ─── Entry point ─────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const key = process.env.INDEXNOW_KEY;

  if (!key) {
    console.log('IndexNow: INDEXNOW_KEY not set — skipping.');
    return;
  }

  // Skip preview and development deployments. VERCEL_ENV is unset in local
  // builds; treat unset the same as "production" only when running on Vercel.
  const vercelEnv = process.env.VERCEL_ENV;
  if (vercelEnv && vercelEnv !== 'production') {
    console.log(`IndexNow: VERCEL_ENV=${vercelEnv} — production only, skipping.`);
    return;
  }

  try {
    const urls = await resolveUrls();

    if (urls.length === 0) {
      console.log('IndexNow: no URLs found in sitemap — skipping.');
      return;
    }

    await submitUrls(urls, key);
    console.log('IndexNow: done.');
  } catch (err) {
    // Non-fatal: log and exit 0 so the build is not blocked.
    console.error(
      'IndexNow: submission error —',
      err instanceof Error ? err.message : err,
    );
  }
}

main();
